# Node role for the instances Karpenter launches on dev-eks-us-east-1.
name: dev-karpenter-node-us-east-1
type: service
description: Node role for instances launched by Karpenter on dev-eks-us-east-1
services: [ec2.amazonaws.com]
policy_arns:
  - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
  - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPullOnly
  - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
